### ISSUE TITLE
chat offline redmine

### ISSUE THREAD

**Issue by ashrafalzyoud** [gtt-project/redmine_chatwoot#6]
thx for your plugin
can your plugin work offline
my server and all my pcs in local network without any internet
and i would like use  your plugin in my redmine

**Comment by dkastl** [comment]
This plugin only provides an integration for a Chatwoot server: https://www.chatwoot.com/
If you can run Chatwoot in your local network, then it should be possible.

**Comment by ashrafalzyoud** [comment]
Thx for replay
 If I'm follow this link in my server redmine Ubuntu 22.04

[https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm]()

This mean your plugin work on offline system?!

Port 3000 I think using in passenger or nginx or redmine?!

**Comment by dkastl** [comment]
I can't tell for sure how well Chatwoot will work in an internal network, but I would assume you can run both, Redmine and Chatwoot in the same network and do the plugin settings accordingly.
